"""
If we list all the natural numbers below 10 that are multiples of 3 or 5, 
we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

Answer: 234168
"""

def sum_multiples_3_5(n=1000):
    res = 0
    for i in range(1, n):
        if i % 3 == 0 or i % 5 == 0:
            res += i
    return res

"""
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.

Answere: 4613732
"""

def even_fib():
    a, b = 0, 1
    fib = []
    while b < 4_000_000:
        a, b = b, a+b
        if b % 2 == 0:
            fib.append(b)
    return sum(fib)

"""
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

Answere: 6857
"""

def largest_prime_factor(n=600851475143):
    factors = []
    d = 2
    while n > 1:
        while n % d == 0:
            factors.append(d)
            n /= d
        d += 1
        if d * d > n:
            if n > 1:
                factors.append(int(n))
            break
    return max(factors)

"""
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

Answere: 906609
"""

def pal_largest_product(n=3):
    start1  = "1" + "0"* (n - 1)
    start2  = "1" + "0"* (n - 1)
    res = -float("inf")
    for i in range(eval(start1), 10**(n)):
        for j in range(eval(start2), 10**(n)):
            product = int(str(i * j))
            if product > res and str(product) == str(product)[::-1]:
                res = product
    return res

"""
2520 is the smallest number that can be divided 
by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible 
by all of the numbers from 1 to 20?

Answer: 232792560
"""

def smallest_multiple(n: range= range(1, 21)):
    res = n.stop
    end = n.stop
    while True: 
        d = n.start
        while res % d == 0 and d != end:
            d += 1
        if d == end:
            break    
        res += end
    return res

"""
Problem 6
Sum Square Difference

Answer: 25164150
"""

def sum_square_diff(n=10):
    sum_natu = (n*(n+1))//2
    res = 0
    for i in range(n+1):
        res += i**2
    return sum_natu**2 - res

if __name__ == "__main__":
    # print(sum_multiples_3_5())
    # print(even_fib())
    # print(largest_prime_factor())
    # print(pal_largest_product(3))
    # print(smallest_multiple(range(1, 21)))
    print(sum_square_diff(100))
